---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - servicemonitor.yml
  - service.yml
  - deployment.yml

configMapGenerator:
  - name: github-exporter
    literals: []

secretGenerator:
  - name: github-exporter
    literals: []

images:
  - name: github-exporter
    newName: quay.io/promhippie/github-exporter
    newTag: latest

...
